// Generates supabase/migrations/0014_editable_everything.sql from the config,
// so the seeded values can never drift from the runtime fallbacks.
//
//   node --experimental-strip-types scripts/gen-0014-migration.mts > supabase/migrations/0014_editable_everything.sql
//
// Two safety properties this migration must have, both enforced here:
//
//  1. page_sections gains five NEW columns. The UPDATEs below only ever write
//     those new columns, never tag/title/subtitle -- so any heading the user
//     has already edited through the CMS survives untouched.
//
//  2. page_section_items gains three NEW sections. The INSERTs are guarded by
//     a NOT EXISTS on (page_slug, section_key), so re-running the migration
//     can't duplicate rows, and the 58 pre-existing items are never touched.

import { SECTION_DEFAULTS, SECTION_FIELDS } from '../lib/page-sections-config.ts'
import { ITEM_DEFAULTS } from '../lib/page-section-items-config.ts'

// The columns being added by this migration -- i.e. everything except the
// three that already existed.
const NEW_SECTION_COLUMNS = SECTION_FIELDS.filter(
  (f) => !['tag', 'title', 'subtitle'].includes(f)
)

// The item sections being added by this migration.
const NEW_ITEM_SECTIONS: [string, string][] = [
  ['about', 'intro'],
  ['home', 'hero_buttons'],
  ['home', 'cta_buttons'],
]

const ITEM_COLUMNS = [
  'page_slug',
  'section_key',
  'display_order',
  'icon',
  'title',
  'subtitle',
  'body',
  'body_suffix',
  'link_href',
  'link_text',
  'anchor_id',
  'value',
  'value_suffix',
  'value_format',
] as const

function sql(v: unknown): string {
  if (v === null || v === undefined) return 'null'
  if (typeof v === 'number') return String(v)
  return `'${String(v).replace(/'/g, "''")}'`
}

const out: string[] = []

out.push(`-- 0014: make the last of the hardcoded page copy editable.
--
-- Generated by scripts/gen-0014-migration.mts -- do not hand-edit; regenerate
-- if the defaults in lib/page-sections-config.ts or
-- lib/page-section-items-config.ts change.

-- 1. Every section can now carry an optional closing note, a call-to-action
--    button, and an empty-state message.`)

for (const col of NEW_SECTION_COLUMNS) {
  out.push(`alter table public.page_sections add column if not exists ${col} text;`)
}

out.push(`
-- 2. Seed the new columns with the copy the site currently ships with, so the
--    public pages look identical after this runs. Only the new columns are
--    written -- existing tag/title/subtitle edits are preserved.`)

for (const [pageSlug, sections] of Object.entries(SECTION_DEFAULTS)) {
  for (const [sectionKey, def] of Object.entries(sections)) {
    const sets = NEW_SECTION_COLUMNS.filter((c) => def.fields.includes(c)).map(
      (c) => `${c} = ${sql(def[c])}`
    )
    if (sets.length === 0) continue
    out.push(
      `update public.page_sections set ${sets.join(', ')}\n` +
        `  where page_slug = ${sql(pageSlug)} and section_key = ${sql(sectionKey)};`
    )
  }
}

out.push(`
-- 3. The Contact page now reads its address from Website Settings instead of
--    hardcoding it, so promote the stored address to the fuller street version
--    the page used to show. Guarded on the old default: if the address has
--    been edited through the CMS, that edit wins and this is a no-op.
update public.website_settings
  set address = ${sql(
    'San Antonio Palico – Balayan – Batangas Road,\nSan Antonio, San Pascual, Batangas, Philippines'
  )}
  where id = 1
    and address = 'San Antonio, San Pascual, Batangas, Philippines';

-- 4. The Contact page's "Contact Information" heading is a new section row.
insert into public.page_sections (page_slug, section_key, title, display_order)
select 'contact', 'info', ${sql(SECTION_DEFAULTS.contact.info.title)}, 2
where not exists (
  select 1 from public.page_sections
  where page_slug = 'contact' and section_key = 'info'
);

-- 5. New editable item sections: the About story paragraphs and the homepage
--    hero / closing-CTA buttons.`)

for (const [pageSlug, sectionKey] of NEW_ITEM_SECTIONS) {
  const items = ITEM_DEFAULTS[pageSlug]?.[sectionKey]
  if (!items) throw new Error(`Missing ITEM_DEFAULTS for ${pageSlug}.${sectionKey}`)

  const values = items.map((item, index) => {
    const record: Record<string, unknown> = {
      page_slug: pageSlug,
      section_key: sectionKey,
      display_order: index + 1,
      ...item,
    }
    return `    (${ITEM_COLUMNS.map((c) => sql(record[c])).join(', ')})`
  })

  out.push(
    `insert into public.page_section_items (${ITEM_COLUMNS.join(', ')})\n` +
      `select * from (values\n${values.join(',\n')}\n  ) as v(${ITEM_COLUMNS.join(', ')})\n` +
      `where not exists (\n` +
      `  select 1 from public.page_section_items\n` +
      `  where page_slug = ${sql(pageSlug)} and section_key = ${sql(sectionKey)}\n);`
  )
}

console.log(out.join('\n\n'))
