-- 0014: make the last of the hardcoded page copy editable.
--
-- Generated by scripts/gen-0014-migration.mts -- do not hand-edit; regenerate
-- if the defaults in lib/page-sections-config.ts or
-- lib/page-section-items-config.ts change.

-- 1. Every section can now carry an optional closing note, a call-to-action
--    button, and an empty-state message.

alter table public.page_sections add column if not exists footnote text;

alter table public.page_sections add column if not exists link_text text;

alter table public.page_sections add column if not exists link_href text;

alter table public.page_sections add column if not exists link_icon text;

alter table public.page_sections add column if not exists empty_text text;


-- 2. Seed the new columns with the copy the site currently ships with, so the
--    public pages look identical after this runs. Only the new columns are
--    written -- existing tag/title/subtitle edits are preserved.

update public.page_sections set link_text = 'View All News', link_href = '/news', empty_text = 'No news articles have been published yet. Check back soon.'
  where page_slug = 'home' and section_key = 'news';

update public.page_sections set link_text = 'Explore Student Life', link_href = '/student-life'
  where page_slug = 'home' and section_key = 'student_life';

update public.page_sections set link_text = 'Or send us a quick inquiry →', link_href = '/contact#contactForm'
  where page_slug = 'home' and section_key = 'cta';

update public.page_sections set link_text = 'Request More Information', link_href = '/contact'
  where page_slug = 'admissions' and section_key = 'intro';

update public.page_sections set footnote = 'See student life in action on our Facebook photo albums.', link_text = 'View Photos on Facebook', link_href = 'https://www.facebook.com/profile.php?id=100057701558010&sk=photos', link_icon = 'fab fa-facebook'
  where page_slug = 'student-life' and section_key = 'intro';

update public.page_sections set footnote = 'Our complete faculty roster is available at the school office.', empty_text = 'Our faculty roster is being updated. Please check back soon.'
  where page_slug = 'faculty' and section_key = 'intro';

update public.page_sections set footnote = 'For real-time updates, announcements, and photos, follow us on Facebook.', link_text = 'Follow Us on Facebook', link_href = 'https://www.facebook.com/p/Gardner-School-of-Multiple-Intelligences-100057701558010/', link_icon = 'fab fa-facebook', empty_text = 'No news articles have been published yet. Check back soon, or follow us on Facebook below.'
  where page_slug = 'news' and section_key = 'intro';

update public.page_sections set link_text = 'Contact Us for These Documents', link_href = '/contact', empty_text = 'Resources are being prepared. Please check back soon, or contact the school office.'
  where page_slug = 'resources' and section_key = 'intro';


-- 3. The Contact page now reads its address from Website Settings instead of
--    hardcoding it, so promote the stored address to the fuller street version
--    the page used to show. Guarded on the old default: if the address has
--    been edited through the CMS, that edit wins and this is a no-op.
update public.website_settings
  set address = 'San Antonio Palico – Balayan – Batangas Road,
San Antonio, San Pascual, Batangas, Philippines'
  where id = 1
    and address = 'San Antonio, San Pascual, Batangas, Philippines';

-- 4. The Contact page's "Contact Information" heading is a new section row.
insert into public.page_sections (page_slug, section_key, title, display_order)
select 'contact', 'info', 'Contact Information', 2
where not exists (
  select 1 from public.page_sections
  where page_slug = 'contact' and section_key = 'info'
);

-- 5. New editable item sections: the About story paragraphs and the homepage
--    hero / closing-CTA buttons.

insert into public.page_section_items (page_slug, section_key, display_order, icon, title, subtitle, body, body_suffix, link_href, link_text, anchor_id, value, value_suffix, value_format)
select * from (values
    ('about', 'intro', 1, null, 'Gardner School of Multiple Intelligences', null, 'is a progressive educational institution located in San Antonio, San Pascual, Batangas. We are committed to providing a holistic approach to education, focusing on the development of children''s multiple intelligences.', null, null, null, null, null, null, null),
    ('about', 'intro', 2, null, null, null, 'Our curriculum is based on the theory of multiple intelligences proposed by Howard Gardner, which suggests that intelligence is not a singular entity, but rather a blend of different abilities. We believe in nurturing the unique talents and strengths of each child.', null, null, null, null, null, null, null),
    ('about', 'intro', 3, null, null, null, 'With a strong emphasis on creativity, critical thinking, and emotional intelligence, we prepare students to become lifelong learners and responsible global citizens.', null, null, null, null, null, null, null)
  ) as v(page_slug, section_key, display_order, icon, title, subtitle, body, body_suffix, link_href, link_text, anchor_id, value, value_suffix, value_format)
where not exists (
  select 1 from public.page_section_items
  where page_slug = 'about' and section_key = 'intro'
);

insert into public.page_section_items (page_slug, section_key, display_order, icon, title, subtitle, body, body_suffix, link_href, link_text, anchor_id, value, value_suffix, value_format)
select * from (values
    ('home', 'hero_buttons', 1, 'fas fa-pen-to-square', 'Enroll Now', null, null, null, '/admissions', null, null, null, null, null),
    ('home', 'hero_buttons', 2, 'fas fa-chevron-down', 'Learn More', null, null, null, '#programs', null, null, null, null, null)
  ) as v(page_slug, section_key, display_order, icon, title, subtitle, body, body_suffix, link_href, link_text, anchor_id, value, value_suffix, value_format)
where not exists (
  select 1 from public.page_section_items
  where page_slug = 'home' and section_key = 'hero_buttons'
);

insert into public.page_section_items (page_slug, section_key, display_order, icon, title, subtitle, body, body_suffix, link_href, link_text, anchor_id, value, value_suffix, value_format)
select * from (values
    ('home', 'cta_buttons', 1, 'fas fa-pen-to-square', 'Enroll Now', null, null, null, '/admissions', null, null, null, null, null),
    ('home', 'cta_buttons', 2, 'fas fa-phone', 'Contact Us', null, null, null, '/contact', null, null, null, null, null)
  ) as v(page_slug, section_key, display_order, icon, title, subtitle, body, body_suffix, link_href, link_text, anchor_id, value, value_suffix, value_format)
where not exists (
  select 1 from public.page_section_items
  where page_slug = 'home' and section_key = 'cta_buttons'
);
